// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBj6TJaQdN0HIHI9f9fvUfIDxx2dh5aU',
    appId: '1:944049282603:web:777e5957a963743b04d46e',
    messagingSenderId: '944049282603',
    projectId: 'stuco-ff938',
    authDomain: 'stuco-ff938.firebaseapp.com',
    storageBucket: 'stuco-ff938.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKjtQ0el-lVY3G9oIQv2A339O-pMpz-w',
    appId: '1:944049282603:android:35fba6682757d7c304d46e',
    messagingSenderId: '944049282603',
    projectId: 'stuco-ff938',
    storageBucket: 'stuco-ff938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxK9ry9olUnvrQbGH4446Dexup7By5WA',
    appId: '1:944049282603:ios:fedc20b600ef69ca04d46e',
    messagingSenderId: '944049282603',
    projectId: 'stuco-ff938',
    storageBucket: 'stuco-ff938.appspot.com',
    androidClientId: '944049282603-bu37cn5m7a7h1puqc6tph8rd3psjsb1e.apps.googleusercontent.com',
    iosClientId: '944049282603-uhckg8919sombo5bjcce0lh5u53d7soc.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUxK9ry9olUnvrQbGH4446Dexup7By5WA',
    appId: '1:944049282603:ios:b1149325aec730eb04d46e',
    messagingSenderId: '944049282603',
    projectId: 'stuco-ff938',
    storageBucket: 'stuco-ff938.appspot.com',
    androidClientId: '944049282603-bu37cn5m7a7h1puqc6tph8rd3psjsb1e.apps.googleusercontent.com',
    iosClientId: '944049282603-dgetopl4h5o92pmst2q1f6mhk68ubmsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyBuddy.RunnerTests',
  );
}
